// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.rebelio_client

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_rebelio_client_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_rebelio_client_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "rebelio_client"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}


































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "rebelio_client")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_rebelio_client_fn_func_add_contact(`nickname`: RustBuffer.ByValue,`routingToken`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_create_group(`name`: RustBuffer.ByValue,`members`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_export_identity(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_get_all_messages(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_get_inbox_messages(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_get_messages(`counterparty`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_get_sent_message_statuses(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_get_status(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_import_identity(`json`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_init_sdk(`storagePath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_load_contacts(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_load_groups(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_mark_messages_read(`messageIds`: RustBuffer.ByValue,`routingToken`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_register_user(`username`: RustBuffer.ByValue,`serverUrl`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_rebelio_client_fn_func_remove_contact(`nickname`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_send_group_message(`groupId`: RustBuffer.ByValue,`messageText`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_send_message(`recipientToken`: RustBuffer.ByValue,`messageText`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_start_realtime_messaging(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_stop_realtime_messaging(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_fn_func_trust_identity(`counterparty`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_rebelio_client_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_rebelio_client_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_rebelio_client_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_rebelio_client_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_rebelio_client_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_rebelio_client_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_rebelio_client_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_rebelio_client_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_rebelio_client_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_rebelio_client_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_rebelio_client_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_rebelio_client_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_rebelio_client_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_rebelio_client_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_rebelio_client_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_rebelio_client_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_rebelio_client_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_rebelio_client_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_rebelio_client_checksum_func_add_contact(
    ): Short
    fun uniffi_rebelio_client_checksum_func_create_group(
    ): Short
    fun uniffi_rebelio_client_checksum_func_export_identity(
    ): Short
    fun uniffi_rebelio_client_checksum_func_get_all_messages(
    ): Short
    fun uniffi_rebelio_client_checksum_func_get_inbox_messages(
    ): Short
    fun uniffi_rebelio_client_checksum_func_get_messages(
    ): Short
    fun uniffi_rebelio_client_checksum_func_get_sent_message_statuses(
    ): Short
    fun uniffi_rebelio_client_checksum_func_get_status(
    ): Short
    fun uniffi_rebelio_client_checksum_func_import_identity(
    ): Short
    fun uniffi_rebelio_client_checksum_func_init_sdk(
    ): Short
    fun uniffi_rebelio_client_checksum_func_load_contacts(
    ): Short
    fun uniffi_rebelio_client_checksum_func_load_groups(
    ): Short
    fun uniffi_rebelio_client_checksum_func_mark_messages_read(
    ): Short
    fun uniffi_rebelio_client_checksum_func_register_user(
    ): Short
    fun uniffi_rebelio_client_checksum_func_remove_contact(
    ): Short
    fun uniffi_rebelio_client_checksum_func_send_group_message(
    ): Short
    fun uniffi_rebelio_client_checksum_func_send_message(
    ): Short
    fun uniffi_rebelio_client_checksum_func_start_realtime_messaging(
    ): Short
    fun uniffi_rebelio_client_checksum_func_stop_realtime_messaging(
    ): Short
    fun uniffi_rebelio_client_checksum_func_trust_identity(
    ): Short
    fun ffi_rebelio_client_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_rebelio_client_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_rebelio_client_checksum_func_add_contact() != 27886.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_create_group() != 646.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_export_identity() != 14521.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_get_all_messages() != 46046.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_get_inbox_messages() != 53884.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_get_messages() != 27908.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_get_sent_message_statuses() != 35239.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_get_status() != 59707.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_import_identity() != 40218.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_init_sdk() != 62688.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_load_contacts() != 36445.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_load_groups() != 42684.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_mark_messages_read() != 21495.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_register_user() != 35952.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_remove_contact() != 42368.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_send_group_message() != 37178.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_send_message() != 35087.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_start_realtime_messaging() != 56847.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_stop_realtime_messaging() != 61114.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rebelio_client_checksum_func_trust_identity() != 450.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * FFI-safe contact type
 */
data class FfiContact (
    var `nickname`: kotlin.String, 
    var `routingToken`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiContact: FfiConverterRustBuffer<FfiContact> {
    override fun read(buf: ByteBuffer): FfiContact {
        return FfiContact(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiContact) = (
            FfiConverterString.allocationSize(value.`nickname`) +
            FfiConverterString.allocationSize(value.`routingToken`)
    )

    override fun write(value: FfiContact, buf: ByteBuffer) {
            FfiConverterString.write(value.`nickname`, buf)
            FfiConverterString.write(value.`routingToken`, buf)
    }
}



/**
 * FFI-safe group type
 */
data class FfiGroup (
    var `id`: kotlin.String, 
    var `name`: kotlin.String, 
    var `members`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiGroup: FfiConverterRustBuffer<FfiGroup> {
    override fun read(buf: ByteBuffer): FfiGroup {
        return FfiGroup(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: FfiGroup) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterSequenceString.allocationSize(value.`members`)
    )

    override fun write(value: FfiGroup, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterSequenceString.write(value.`members`, buf)
    }
}



/**
 * FFI-safe message type
 */
data class FfiMessage (
    var `id`: kotlin.String, 
    var `sender`: kotlin.String, 
    var `content`: kotlin.String, 
    var `timestamp`: kotlin.Long, 
    var `isEncrypted`: kotlin.Boolean, 
    var `status`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiMessage: FfiConverterRustBuffer<FfiMessage> {
    override fun read(buf: ByteBuffer): FfiMessage {
        return FfiMessage(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiMessage) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`sender`) +
            FfiConverterString.allocationSize(value.`content`) +
            FfiConverterLong.allocationSize(value.`timestamp`) +
            FfiConverterBoolean.allocationSize(value.`isEncrypted`) +
            FfiConverterString.allocationSize(value.`status`)
    )

    override fun write(value: FfiMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`sender`, buf)
            FfiConverterString.write(value.`content`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
            FfiConverterBoolean.write(value.`isEncrypted`, buf)
            FfiConverterString.write(value.`status`, buf)
    }
}



/**
 * FFI-safe status type
 */
data class FfiStatus (
    var `isRegistered`: kotlin.Boolean, 
    var `username`: kotlin.String?, 
    var `routingToken`: kotlin.String?, 
    var `serverUrl`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiStatus: FfiConverterRustBuffer<FfiStatus> {
    override fun read(buf: ByteBuffer): FfiStatus {
        return FfiStatus(
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiStatus) = (
            FfiConverterBoolean.allocationSize(value.`isRegistered`) +
            FfiConverterOptionalString.allocationSize(value.`username`) +
            FfiConverterOptionalString.allocationSize(value.`routingToken`) +
            FfiConverterString.allocationSize(value.`serverUrl`)
    )

    override fun write(value: FfiStatus, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`isRegistered`, buf)
            FfiConverterOptionalString.write(value.`username`, buf)
            FfiConverterOptionalString.write(value.`routingToken`, buf)
            FfiConverterString.write(value.`serverUrl`, buf)
    }
}



/**
 * FFI-safe status update for message delivery/read receipts
 */
data class FfiStatusUpdate (
    var `messageId`: kotlin.String, 
    var `status`: kotlin.String, 
    var `timestamp`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiStatusUpdate: FfiConverterRustBuffer<FfiStatusUpdate> {
    override fun read(buf: ByteBuffer): FfiStatusUpdate {
        return FfiStatusUpdate(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: FfiStatusUpdate) = (
            FfiConverterString.allocationSize(value.`messageId`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterLong.allocationSize(value.`timestamp`)
    )

    override fun write(value: FfiStatusUpdate, buf: ByteBuffer) {
            FfiConverterString.write(value.`messageId`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterLong.write(value.`timestamp`, buf)
    }
}





/**
 * FFI-safe error type
 */
sealed class RebelioException: kotlin.Exception() {
    
    class NotRegistered(
        ) : RebelioException() {
        override val message
            get() = ""
    }
    
    class NetworkException(
        
        val v1: kotlin.String
        ) : RebelioException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class CryptoException(
        
        val v1: kotlin.String
        ) : RebelioException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class StorageException(
        
        val v1: kotlin.String
        ) : RebelioException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class InvalidInput(
        
        val v1: kotlin.String
        ) : RebelioException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class Unknown(
        
        val v1: kotlin.String
        ) : RebelioException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<RebelioException> {
        override fun lift(error_buf: RustBuffer.ByValue): RebelioException = FfiConverterTypeRebelioError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeRebelioError : FfiConverterRustBuffer<RebelioException> {
    override fun read(buf: ByteBuffer): RebelioException {
        

        return when(buf.getInt()) {
            1 -> RebelioException.NotRegistered()
            2 -> RebelioException.NetworkException(
                FfiConverterString.read(buf),
                )
            3 -> RebelioException.CryptoException(
                FfiConverterString.read(buf),
                )
            4 -> RebelioException.StorageException(
                FfiConverterString.read(buf),
                )
            5 -> RebelioException.InvalidInput(
                FfiConverterString.read(buf),
                )
            6 -> RebelioException.Unknown(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: RebelioException): ULong {
        return when(value) {
            is RebelioException.NotRegistered -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is RebelioException.NetworkException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is RebelioException.CryptoException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is RebelioException.StorageException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is RebelioException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is RebelioException.Unknown -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: RebelioException, buf: ByteBuffer) {
        when(value) {
            is RebelioException.NotRegistered -> {
                buf.putInt(1)
                Unit
            }
            is RebelioException.NetworkException -> {
                buf.putInt(2)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is RebelioException.CryptoException -> {
                buf.putInt(3)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is RebelioException.StorageException -> {
                buf.putInt(4)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is RebelioException.InvalidInput -> {
                buf.putInt(5)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is RebelioException.Unknown -> {
                buf.putInt(6)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiContact: FfiConverterRustBuffer<List<FfiContact>> {
    override fun read(buf: ByteBuffer): List<FfiContact> {
        val len = buf.getInt()
        return List<FfiContact>(len) {
            FfiConverterTypeFfiContact.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiContact>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiContact.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiContact>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiContact.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiGroup: FfiConverterRustBuffer<List<FfiGroup>> {
    override fun read(buf: ByteBuffer): List<FfiGroup> {
        val len = buf.getInt()
        return List<FfiGroup>(len) {
            FfiConverterTypeFfiGroup.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiGroup>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiGroup.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiGroup>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiGroup.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiMessage: FfiConverterRustBuffer<List<FfiMessage>> {
    override fun read(buf: ByteBuffer): List<FfiMessage> {
        val len = buf.getInt()
        return List<FfiMessage>(len) {
            FfiConverterTypeFfiMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiMessage>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiMessage.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiStatusUpdate: FfiConverterRustBuffer<List<FfiStatusUpdate>> {
    override fun read(buf: ByteBuffer): List<FfiStatusUpdate> {
        val len = buf.getInt()
        return List<FfiStatusUpdate>(len) {
            FfiConverterTypeFfiStatusUpdate.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiStatusUpdate>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiStatusUpdate.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiStatusUpdate>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiStatusUpdate.write(it, buf)
        }
    }
}
        /**
         * Add a contact
         */
    @Throws(RebelioException::class) fun `addContact`(`nickname`: kotlin.String, `routingToken`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_add_contact(
        FfiConverterString.lower(`nickname`),FfiConverterString.lower(`routingToken`),_status)
}
    
    

        /**
         * Create a group
         */
    @Throws(RebelioException::class) fun `createGroup`(`name`: kotlin.String, `members`: List<kotlin.String>): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_create_group(
        FfiConverterString.lower(`name`),FfiConverterSequenceString.lower(`members`),_status)
}
    )
    }
    

        /**
         * Export identity for backup/transfer to another device
         * Returns JSON string that can be encoded as QR code
         */
    @Throws(RebelioException::class) fun `exportIdentity`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_export_identity(
        _status)
}
    )
    }
    

        /**
         * Get all messages from all chats (flat list)
         * Use this to load history at startup
         */
    @Throws(RebelioException::class) fun `getAllMessages`(): List<FfiMessage> {
            return FfiConverterSequenceTypeFfiMessage.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_get_all_messages(
        _status)
}
    )
    }
    

        /**
         * Get inbox messages
         */
    @Throws(RebelioException::class) fun `getInboxMessages`(): List<FfiMessage> {
            return FfiConverterSequenceTypeFfiMessage.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_get_inbox_messages(
        _status)
}
    )
    }
    

        /**
         * Get messages for a specific contact (from encrypted storage)
         */
    @Throws(RebelioException::class) fun `getMessages`(`counterparty`: kotlin.String): List<FfiMessage> {
            return FfiConverterSequenceTypeFfiMessage.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_get_messages(
        FfiConverterString.lower(`counterparty`),_status)
}
    )
    }
    

        /**
         * Get statuses of sent messages from local history
         * Use this for polling-based status sync on Android
         */
    @Throws(RebelioException::class) fun `getSentMessageStatuses`(): List<FfiStatusUpdate> {
            return FfiConverterSequenceTypeFfiStatusUpdate.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_get_sent_message_statuses(
        _status)
}
    )
    }
    

        /**
         * Get current status
         */
    @Throws(RebelioException::class) fun `getStatus`(): FfiStatus {
            return FfiConverterTypeFfiStatus.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_get_status(
        _status)
}
    )
    }
    

        /**
         * Import identity from backup JSON
         * After import, call register_user() to re-authenticate with server
         */
    @Throws(RebelioException::class) fun `importIdentity`(`json`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_import_identity(
        FfiConverterString.lower(`json`),_status)
}
    
    

        /**
         * Initialize the SDK with specific storage path (required for Android)
         */
    @Throws(RebelioException::class) fun `initSdk`(`storagePath`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_init_sdk(
        FfiConverterString.lower(`storagePath`),_status)
}
    
    

        /**
         * Load contacts
         */
    @Throws(RebelioException::class) fun `loadContacts`(): List<FfiContact> {
            return FfiConverterSequenceTypeFfiContact.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_load_contacts(
        _status)
}
    )
    }
    

        /**
         * Load groups
         */
    @Throws(RebelioException::class) fun `loadGroups`(): List<FfiGroup> {
            return FfiConverterSequenceTypeFfiGroup.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_load_groups(
        _status)
}
    )
    }
    

        /**
         * Mark messages as read and send read receipts to the server
         */
    @Throws(RebelioException::class) fun `markMessagesRead`(`messageIds`: List<kotlin.String>, `routingToken`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_mark_messages_read(
        FfiConverterSequenceString.lower(`messageIds`),FfiConverterString.lower(`routingToken`),_status)
}
    
    

        /**
         * Register a new user with the server
         */
    @Throws(RebelioException::class) fun `registerUser`(`username`: kotlin.String, `serverUrl`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_register_user(
        FfiConverterString.lower(`username`),FfiConverterString.lower(`serverUrl`),_status)
}
    )
    }
    

        /**
         * Remove a contact
         */
    @Throws(RebelioException::class) fun `removeContact`(`nickname`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_remove_contact(
        FfiConverterString.lower(`nickname`),_status)
}
    
    

        /**
         * Send a group message
         */
    @Throws(RebelioException::class) fun `sendGroupMessage`(`groupId`: kotlin.String, `messageText`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_send_group_message(
        FfiConverterString.lower(`groupId`),FfiConverterString.lower(`messageText`),_status)
}
    
    

        /**
         * Send an encrypted message
         */
    @Throws(RebelioException::class) fun `sendMessage`(`recipientToken`: kotlin.String, `messageText`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_send_message(
        FfiConverterString.lower(`recipientToken`),FfiConverterString.lower(`messageText`),_status)
}
    
    

        /**
         * Start real-time messaging service (WebSocket)
         * Call this after login/register to start receiving messages instantly
         */
    @Throws(RebelioException::class) fun `startRealtimeMessaging`()
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_start_realtime_messaging(
        _status)
}
    
    

        /**
         * Stop real-time messaging service
         * Call this on logout or app background (if desired)
         */ fun `stopRealtimeMessaging`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_stop_realtime_messaging(
        _status)
}
    
    

        /**
         * Trust a contact's new identity and reset session
         * Call this when user confirms they trust the new identity key
         */
    @Throws(RebelioException::class) fun `trustIdentity`(`counterparty`: kotlin.String)
        = 
    uniffiRustCallWithError(RebelioException) { _status ->
    UniffiLib.INSTANCE.uniffi_rebelio_client_fn_func_trust_identity(
        FfiConverterString.lower(`counterparty`),_status)
}
    
    


